apiVersion: {{ .Values.api.app }}
kind: {{ .Values.kind.deploy }}
metadata:
  name: {{ .Values.label.app }}
  namespace: {{ .Values.namespace.travel }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.label.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.label.app }}
    spec:
      containers:
      - name: {{ .Values.label.app }}
        image: {{ .Values.images.backendauth.repository }}:{{ .Values.images.backendauth.tag }}
        envFrom:
         - configMapRef:
             name: {{ .Values.config.mysql }}
        ports:
        - containerPort: {{ .Values.service.port }}
