apiVersion: {{ .Values.api.v1 }}
kind: {{ .Values.kind.config }}
metadata:
  name: {{ .Values.label.config }}
  namespace: {{ .Values.namespace.travel }}
data:
  environment.ts: |
{{ .Values.configMap.environmentTs | indent 4 }}
  environment.prod.ts: |
{{ .Values.configMap.environmentProdTs | indent 4 }}
