---
# Source: fe/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: front-end-config
  namespace: travel
data:
  environment.ts: |
    window['environmentauth'] = {
      production: false,
      apiUrl: 'http://backend-auth-service:5000'
    };
    window['environmenttours'] = {
      production: false,
      apiUrl: 'http://backend-tours-service:5001'
    };
    
  environment.prod.ts: |
    window['environmentauth'] = {
      production: true,
      apiUrl: 'http://backend-auth-service:5000'
    };
    window['environmenttours'] = {
      production: true,
      apiUrl: 'http://backend-tours-service:5001'
    };
---
# Source: fe/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  namespace: travel
spec:
  selector:
    app: front-end
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
---
# Source: fe/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-web
  namespace: travel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end
      version: v1
  template:
    metadata:
      labels:
        app: front-end
        version: v1
    spec:
      containers:
      - name: front-end
        image: samuelrak/fe-git:main
#        image: samuelrak/travel:t-fe20
        ports:
        - containerPort: 80
#        volumeMounts:
#        - name: config-volume
#          mountPath: /app/src/environments
        env:
          - name: API_URL_AUTH
            value: http://mytravel-123.com/login
#      volumes:
#      - name: config-volume
#        configMap:
#          name: frontend-config
---
# Source: fe/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-fe
  labels:
    helm.sh/chart: fe-0.1.0
    app.kubernetes.io/name: fe
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/version: "1.3"
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-fe
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
# Source: fe/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-fe
  labels:
    helm.sh/chart: fe-0.1.0
    app.kubernetes.io/name: fe
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/version: "1.3"
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "travel.com"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend-fe
                port:
                  number: 4200
---
# Source: fe/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "frontend-fe-test-connection"
  labels:
    helm.sh/chart: fe-0.1.0
    app.kubernetes.io/name: fe
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/version: "1.3"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['frontend-fe:4200']
  restartPolicy: Never
