---
# Source: be-auth/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-auth-service
  namespace: travel
spec:
  selector:
    app: backend-auth
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
# Source: be-auth/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-auth
  namespace: travel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-auth
  template:
    metadata:
      labels:
        app: backend-auth
    spec:
      containers:
      - name: backend-auth
        image: samuelrak/be-auth-git:main
        envFrom:
         - configMapRef:
             name: mysql-config
        ports:
        - containerPort: 5000
---
# Source: be-auth/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backauth-be-auth
  labels:
    helm.sh/chart: be-auth-0.1.0
    app.kubernetes.io/name: be-auth
    app.kubernetes.io/instance: backauth
    app.kubernetes.io/version: "1.4"
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backauth-be-auth
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
# Source: be-auth/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backauth-be-auth
  labels:
    helm.sh/chart: be-auth-0.1.0
    app.kubernetes.io/name: be-auth
    app.kubernetes.io/instance: backauth
    app.kubernetes.io/version: "1.4"
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "travel.com"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: backauth-be-auth
                port:
                  number: 5000
---
# Source: be-auth/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "backauth-be-auth-test-connection"
  labels:
    helm.sh/chart: be-auth-0.1.0
    app.kubernetes.io/name: be-auth
    app.kubernetes.io/instance: backauth
    app.kubernetes.io/version: "1.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['backauth-be-auth:5000']
  restartPolicy: Never
