apiVersion: v2
dependencies:
  - name: be-auth
    version: 0.1.0
    repository: "https://gitlab.kosickaakademia.sk/Samuel.Rak/helm-git"

  - name: be-tours
    version: 0.1.1
    repository: "https://gitlab.kosickaakademia.sk/Samuel.Rak/helm-git"

  - name: db
    version: 0.1.0
    repository: "https://gitlab.kosickaakademia.sk/Samuel.Rak/helm-git"

  - name: fe
    version: 0.1.13
    repository: "https://gitlab.kosickaakademia.sk/Samuel.Rak/helm-git"
