api:
  app: apps/v1
  v1: v1

image:
  mydockerhub:
    repository: samuelrak/be-auth-git
    version: main

namespace:
  travel: travel

replicas: 1

kind:
  deploy: Deployment
  service: Service
  secret: Secret
  config: ConfigMap
  pvc: PersistentVolumeClaim

service:
  type: ClusterIP
  port: 5000
  protocol: TCP

label:
  app: backend-auth
  service: backend-auth-service

config:
  mysql: mysql-config

serviceAccount:
  create: true
  name: my-travel
  annotations:
    example.com/annotation: "value"
  automount: true

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: travel.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
