apiVersion: {{ .Values.api.app }}
kind: {{ .Values.kind.deploy }}
metadata:
  name: {{ .Values.label.app }}
  namespace: {{ .Values.namespace.travel }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.label.app }}
      version: {{ .Values.api.v1 }}
  template:
    metadata:
      labels:
        app: {{ .Values.label.app }}
        version: {{ .Values.api.v1 }}
    spec:
      containers:
      - name: {{ .Values.label.app }}
        image: {{ .Values.image.mydockerhub.repository }}:{{ .Values.image.mydockerhub.version }}
#        image: samuelrak/travel:t-fe20
        ports:
        - containerPort: {{ .Values.service.containerport }}
#        volumeMounts:
#        - name: config-volume
#          mountPath: /app/src/environments
        env:
          - name: API_URL_AUTH
            value: http://mytravel-123.com/login
#      volumes:
#      - name: config-volume
#        configMap:
#          name: frontend-config
